#!/bin/bash
CURRENT_PATH=`pwd`;
CHANNEL_INFO_PARENT_DIRECTORY_NAME="META-INF"
CHANNEL_APK_PARENT_DIRECTORY_NAME="out"
CHANNELS_LIST_FILE_NAME="channels.config"
CHANNEL_PREFIX_NAME="jdjk_"
CURRNT_TIME=`date +%Y%m%d%H%M%S`
SERVER_HOST=$1


echo "CURRENT_PATH = $CURRENT_PATH"
echo "CHANNEL_INFO_PARENT_DIRECTORY_NAME = $CHANNEL_INFO_PARENT_DIRECTORY_NAME"
echo "CHANNEL_APK_PARENT_DIRECTORY_NAME = $CHANNEL_APK_PARENT_DIRECTORY_NAME"
echo "CHANNELS_LIST_FILE_NAME = $CHANNELS_LIST_FILE_NAME"
echo "CHANNEL_PREFIX_NAME = $CHANNEL_PREFIX_NAME"
echo "CURRNT_TIME = $CURRNT_TIME"
echo "SERVER_HOST = $SERVER_HOST"


currntPathBaseName=`basename $CURRENT_PATH`
if [ $currntPathBaseName != multiChannelBuild ]; then
	echo "请在multiChannelBuild目录下执行该脚本"
	exit 1
fi

if [ ! -e ${CHANNELS_LIST_FILE_NAME} ]; then
	echo "没有渠道列表文件"
	exit 1
fi

if [ `ls -al *.apk | wc -l` -gt 1 ]; then
	echo "当前目录下有多个apk文件";
	exit 1
elif [ `ls -al *.apk | wc -l` -lt 1 ]; then
	echo "当前目录下没有apk文件";
	exit 1
else
	echo ""
fi

#原应用名字
originApkFileName=`ls *.apk`
originApkFileBaseName=`basename $originApkFileName .apk`
#加固后apk名字
originSignedApkFileName=${originApkFileBaseName}_signed.apk



#加固
java  -jar jiagu/jiagu.jar -login jdjk_tech@jiandanjiekuan.com jdjk_tech2016
java  -jar jiagu/jiagu.jar -jiagu ./$originApkFileName ./
if [ `ls -al *.apk | wc -l` -eq 2 ]; then
	for child in *.apk;
	do
		if [ $child != $originApkFileName ]; then
			signedTmpApkFile=$child;
		fi
	done
else
	echo "加固出错了，当前目录下apk的数量不为2"
	exit 1
fi

cp $signedTmpApkFile ${originSignedApkFileName}

#开始签名、zipalign
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore sudaixiong.jks $originSignedApkFileName sudaixiongkey -storepass sudaixiong
zipalign -v -p 4 $originSignedApkFileName "temp_"$originSignedApkFileName
rm $originSignedApkFileName
mv "temp_"$originSignedApkFileName $originSignedApkFileName

echo "\n\n\n"
echo "\n  #### 开始生成渠道包 ####"
echo "原始apk文件名字："$originSignedApkFileName

#放置apk文件的目录
mkdir -p $CHANNEL_APK_PARENT_DIRECTORY_NAME
mkdir -p $CHANNEL_INFO_PARENT_DIRECTORY_NAME

rm -rf ${CHANNEL_APK_PARENT_DIRECTORY_NAME}/*
while IFS='' read -r line || [[ -n "$line" ]];
do
	#channelCategory=`echo $line | cut -d ':' -f 1`
	channelCategoryItems=$line #`echo $line | cut -d ':' -f 2`
	#echo "    ++++++++ 渠道类别："$channelCategory
	echo "    ++++++++ 渠道列表："$channelCategoryItems
	#if [ -n $channelCategory ]; then
		#mkdir -p ${CHANNEL_APK_PARENT_DIRECTORY_NAME}/${channelCategory}
		OLD_IFS="$IFS";
		IFS=",";
		channelArray=($channelCategoryItems);
		IFS="$OLD_IFS"
		for channel in ${channelArray[@]}
		do
			echo "        开始生成渠道包：${channel}"
			rm ${CHANNEL_INFO_PARENT_DIRECTORY_NAME}/*
			encryptedChannel=`md5 -q -s ${channel}napgnaw`
			encryptedChannel=`echo ${encryptedChannel:0:5}`
			touch ${CHANNEL_INFO_PARENT_DIRECTORY_NAME}/${CHANNEL_PREFIX_NAME}${encryptedChannel}_${channel}
			newChannelApkFileName=${channel}_${originApkFileBaseName}_${SERVER_HOST}_${CURRNT_TIME}.apk
			cp $originSignedApkFileName $newChannelApkFileName
			zip -ur $newChannelApkFileName ${CHANNEL_INFO_PARENT_DIRECTORY_NAME}
			mv $newChannelApkFileName ${CHANNEL_APK_PARENT_DIRECTORY_NAME}/$newChannelApkFileName
		done
	#fi
done < $CHANNELS_LIST_FILE_NAME

# rm *.apk
# rm -rf $CHANNEL_APK_PARENT_DIRECTORY_NAME
